### ISSUE TITLE
Add support for attributes and events.

### ISSUE THREAD

**Issue by UrsZeidler** [adridadou/eth-contract-api#34]
After playing around a bit, nice work btw. thanks for it, I notice than currently only  functions are supported, do you plan to add attributes and events as well ?

May be I have overlooked it.

**Comment by adridadou** [comment]
Hi!
thanks happy you like it.
For the events, I had a PR that added the feature. you can find it by calling events() in your EthereumFacade

Attributes ... I am not sure what you are referring to. Can you elaborate ?

**Comment by UrsZeidler** [comment]
Sorry for being unclear, by attributes I mean the contract attributes, but never mind, my fault, I expected the name of the attribute accessors to be get\[attribute.name.firstUpperCase()\]() and not \[attribute.name\]().
Looking closer to the source it's obvious. 

By Events I mean the contract events , may be I don't look hard enough, I'm looking for something simmular to 

	var event_VersionChecksum = contract.VersionChecksum({},{fromBlock: 0});
	event_VersionChecksum.watch(function(error,result){....

in web3js.

**Comment by adridadou** [comment]
So this would be the events() method from the EthereumFacade (the object created by the Provider)

For the attributes ... we could do something but you are right it is not done yet. Especially because it is easy to create a simple getter and call it. 

If you feel that being able to read the attributes directly (without getters) is important, please create a new issue.

I still have to write the documentation for the events. I close this issue and feel free to create a new one for each separate point
