### ISSUE TITLE
getNonce before sync is done

### ISSUE THREAD

**Issue by kivanov82** [adridadou/eth-contract-api#58]
A small one but.
If getNonce() is called before the sync is done it returns potentially incorrect one since a few transactions might have been called already.
I think we should wait and return nothing until synchronization is done.

**Comment by adridadou** [comment]
I see your point but this is a limitation that you don't necessarily want.

Imagine you want to be able to do offline transactions signing. You need the nonce up to this point, you know that even if you're not fully synced it will be correct because it is your account. 

Also, you have the information, you know if the synchro has been done or not.

What behavior do you expect ?

**Comment by kivanov82** [comment]
You're right it's more importatnt to have a possibility to sign transactions before sync is complete.
In my particular case I use nonce as a param for my function, a sort of id in the contract.
Perhaps I will use something else or will add Future on sync in my code

**Comment by adridadou** [comment]
My suggestion would be, you use the onReady CompletableFuture and you compose it with the call. This way you get your nonce only when it is ready.

Can you close the issue if you're ok with the current situation?

**Comment by kivanov82** [comment]
Yep, thanks
