### ISSUE TITLE
stress tests

### ISSUE THREAD

**Issue by adridadou** [adridadou/eth-contract-api#86]
It seems that if we create too many tx per sec, the system becomes unstable and most if not all the txs are being dropped.

I need to test that and see if I can resolve the isuse

**Comment by kivanov82** [comment]
The root cause is the wrong way how required nonce is calculated. Currently, we take the nonce from repository and add the amount of 'pending' transactions. However, on the next transaction scheduling it can happen that previous trancastion already increased nonce in the repo and hasn't decrease the map of 'pending'. So that next transaction will be called with 'previous nonce' +2

**Comment by kivanov82** [comment]
We need to keep in sync changes in Ethereum Repo and amount of items in the map of 'pending'
